language: php

php:
  - 5.6
  - 7.2

services:
  - docker

before_script:
  - composer install -n --prefer-dist --dev 
  - docker pull kennethreitz/httpbin
  - docker run -d --rm -p 80:80 kennethreitz/httpbin

script: ./vendor/bin/phpunit --coverage-clover=coverage.xml
